### ISSUE TITLE
Ubuntu install error with DEB package

### ISSUE THREAD

**Issue by geoffmcl** [htacg/html-tidy.org.binaries#1]
20160324: This issue has been moved from [issue 344](https://github.com/htacg/tidy-html5/issues/344) to here!

@CuthbertJungle commented on Jan 7, 2016

http://binaries.html-tidy.org/binaries/tidy-5.1.25/tidy-5.1.25-64bit.deb

Error message:
The package is of bad quality.

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /home/david/Downloads/tidy-5.1.25-64bit.deb:
E: tidy: control-file-has-bad-permissions md5sums 0664 != 0644
E: tidy: maintainer-name-missing maintainer@htacg.org
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.

@sataris commented on Jan 18, 2016

@geoffmcl I believe the md5sum error is fixed from CMake 3.3+

Now that the actual package building has been moved out of the main source repo, to here, we have a chance to use other packaging methods, other than cmake.

In any case we have concluded the CMake/CPack packaging is **too rudimentary** for both Windows and MAC OS X, and are already planning alternative `packaging` for those systems...

@CuthbertJungle we are considering a new release 5.2 shortly, and will try to certainly take care that any package we generate for unix passes the lintian tests... thanks for the report...

**Comment by geoffmcl** [comment]
@CuthbertJungle, @sataris I have started to experiment with this and wrote the following rough script, `mkdeb.sh`, to see what happens, using the information from this [link](http://ubuntuforums.org/showthread.php?t=910717). Maybe others can point me to some better tutorial links?

But you should be able to put it in any folder, mark it executable, and run it -

``` bash
#!/bin/sh
#< mkdeb.sh
BN=`basename $0`
TMPREPO="git@github.com:htacg/tidy-html5.git"
TMPDIR="tidy-html5"
TMPFIL="version.txt"
CWD="$(pwd)"
TMPCTL="control"
TMPLOG="$CWD/bldlog-u.txt"

if [ -f "$TMPLOG" ]; then
    rm -f "$TMPLOG"
fi

echo "$BN: Update $TMPDIR, in $CWD"
if [ -d "$TMPDIR" ]; then
    cd "$TMPDIR"
    echo "$BN: Doing 'git pull' in $(pwd)..."
    git pull
else
    echo "$BN: Doing 'git clone $TMPREPO $TMPDIR'..."
    git clone $TMPREPO $TMPDIR
    cd "$TMPDIR"
fi
if [ ! -f "$TMPFIL" ]; then
    echo "$BN: Can NOT locate $TMPFIL!"
    exit 1
fi

echo "$BN: Getting version and architecture..."
TMPARCH=`uname -m`
# TMPVER=$(cat version.txt)
while read line; do
    TMPVER="$line"
    break
done < "$TMPFIL"
echo "$BN: Version '$TMPVER' arch '$TMPARCH'"
TMPDIR2="tidy-$TMPVER-$TMPARCH"
echo "$BN: DEB directory '$TMPDIR2'"
# TMPINST="$CWD/$TMPDIR2"
# TMPINST="$CWD/$TMPDIR2/usr/local"
TMPINST="$CWD/$TMPDIR2/usr"
#TMPDEB="tidy-5.1.47-x86_64.deb"
TMPDEB="$TMPDIR2.deb"

cd build/cmake
echo "$BN: Doing 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TMPINST'"
echo "$BN: Doing 'cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TMPINST'" >> "$TMPLOG"
cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TMPINST >> $TMPLOG 2>&1
if [ ! "$?" = "0" ]; then
    echo "$BN: cmake configuration or generation FAILED!"
    exit 1
fi
echo "$BN: Doing 'make'"
echo "$BN: Doing 'make'" >> "$TMPLOG"
make >> "$TMPLOG" 2>&1
if [ ! "$?" = "0" ]; then
    echo "$BN: make FAILED!"
    echo "$BN: make FAILED!" >> "$TMPLOG"
    exit 1
fi
if [ -d "$TMPINST" ]; then
    echo "$BN: Removing last install..."
    sudo rm -rf "$TMPINST"
else
    echo "$BN: No previous install"
fi

# echo "$BN: Doing 'sudo make install'"
# sudo make install
echo "$BN: Doing 'make install'"
echo "$BN: Doing 'make install'" >> "$TMPLOG"
make install >> "$TMPLOG" 2>&1
if [ ! "$?" = "0" ]; then
    echo "$BN: make install FAILED!"
    echo "$BN: make install FAILED!" >> "$TMPLOG"
    exit 1
fi
# get back to root
cd "$CWD"
if [ ! -d "$TMPDIR2" ]; then
    echo "$BN: Install to $TMPDIR2 FAILED!"
    exit 1
fi
mkdir "$TMPDIR2/DEBIAN"

echo "$BN: Writing DEBIAN/$TMPCTL"
cat <<EOT > "$TMPDIR2/DEBIAN/$TMPCTL"
Package: tidy
Version: $TMPVER
Section: base
Priority: optional
Architecture: $TMPARCH
Depends: libc (>= 6.0.0)
Maintainer: Geoff R. McLane <ubuntu@geoffair.info>
Description: HTML Tidy
 Release version $TMPVER-$TMPARCH
EOT

if [ ! -f "$TMPDIR2/DEBIAN/$TMPCTL" ]; then
    echo "$BN: Failed to write '$TMPDIR2/DEBIAN/$TMPCTL'!"
    exit 1
fi
if [ -f "$TMPDEB" ]; then
    echo "$BN: Removing last $TMPDEB"
    rm "$TMPDEB"
fi

echo "$BN: Running 'dpkg-deb --build $TMPDIR2'"
dpkg-deb --build $TMPDIR2
if [ ! "$?" = "0" ]; then
    echo "$BN: dpkg-deb FAILED!"
    exit 1
fi

if [ ! -f "$TMPDEB" ]; then
    echo "$BN: Appears creation of '$TMPDEB' FAILED!"
    exit 1
fi

echo "$BN: Appears a successful DEB build... $TMPDEB"
echo "$BN: Appears a successful DEB build... $TMPDEB" >> "$TMPLOG"
echo "$BN: Doing: 'lintian $TMPDEB'" >> $TMPLOG 2>&1
echo "=========================" >> "$TMPLOG"
lintian $TMPDEB >> $TMPLOG 2>&1
if [ ! "$?" = "0" ]; then
    echo "=========================" >> "$TMPLOG"
    echo "$BN: lintian FAILED. See $TMPLOG"
    exit 1
fi
echo "=========================" >> "$TMPLOG"
echo "$BN: All done... see $TMPLOG"
echo "$BN: All done..." >> "$TMPLOG"
echo "" >> "$TMPLOG"

# eof
```

In Ubuntu it seems to successfully build `tidy-5.1.47-x86_64.deb`, with only one warning from `dpkg-deb` that the architexture `x86_64` is not valid... Anyone know what I should use instead of `uname -m`?

The contents looks good with `dpkg-deb -l <deb>`, but WOW, lintian complains about a **lot** of things...

```
mkdeb.sh: Doing: 'lintian tidy-5.1.47-x86_64.deb'
=========================
W: tidy: package-name-doesnt-match-sonames libtidy5
E: tidy: unstripped-binary-or-object usr/bin/tidy
E: tidy: unstripped-binary-or-object usr/lib/libtidy.so.5.1.47
E: tidy: missing-dependency-on-libc needed by usr/bin/tidy and 1 others
E: tidy: changelog-file-missing-in-native-package
E: tidy: no-copyright-file
W: tidy: unknown-architecture x86_64
W: tidy: unknown-section base
E: tidy: wrong-file-owner-uid-or-gid usr/ 1000/1000
W: tidy: non-standard-dir-perm usr/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/bin/ 1000/1000
W: tidy: non-standard-dir-perm usr/bin/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/bin/tidy 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/include/ 1000/1000
W: tidy: non-standard-dir-perm usr/include/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/include/tidy.h 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/include/tidybuffio.h 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/include/tidyenum.h 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/include/tidyplatform.h 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/lib/ 1000/1000
W: tidy: non-standard-dir-perm usr/lib/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/lib/libtidy.so 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/lib/libtidy.so.5 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/lib/libtidy.so.5.1.47 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/lib/libtidys.a 1000/1000
E: tidy: wrong-file-owner-uid-or-gid usr/share/ 1000/1000
W: tidy: non-standard-dir-perm usr/share/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/share/man/ 1000/1000
W: tidy: non-standard-dir-perm usr/share/man/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/share/man/man1/ 1000/1000
W: tidy: non-standard-dir-perm usr/share/man/man1/ 0775 != 0755
E: tidy: wrong-file-owner-uid-or-gid usr/share/man/man1/tidy.1 1000/1000
E: tidy: manpage-not-compressed usr/share/man/man1/tidy.1
W: tidy: non-dev-pkg-with-shlib-symlink usr/lib/libtidy.so.5.1.47 usr/lib/libtidy.so
E: tidy: no-shlibs-control-file usr/lib/libtidy.so.5.1.47
E: tidy: postinst-must-call-ldconfig usr/lib/libtidy.so.5.1.47
=========================
```

Now some things look easy to fix, if you know how, but I don't, and seek some advice, pointers, ideas, etc... Especially the first W: - where is it getting the name `libtidy5` from?

Other things... 
- How to `stip` these files? I used `Release` in cmake?
- I suppose I could cut the head of tidy.h and write it to I assume a `COPYRIGHT` file...
- And I suppose I could generate a `CHANGELOG`, if that is what it is looking for?
- As already mentioned, what are the allowed architecture? Where do I get this from?
- What owner uid or gid should the files have? root, or what?
- I suppose I could add something to the script to change permissions. Does it want 775 or  755?
- And I suppose I could also script compressing tidy.1
- Completely lost on the shlib symlink problem?
- What shlibs control files does it want?
- What this about postinst call to ldconfig?

Just as another trial I also ran it in my RPI Raspbian machine, this time as root, but got a similar list of complaints -

```
mkdeb.sh: Appears a successful DEB build... tidy-5.1.47-armv7l.deb
mkdeb.sh: Doing: 'lintian tidy-5.1.47-armv7l.deb'
=========================
warning: the authors of lintian do not recommend running it with root privileges!
W: tidy: package-name-doesnt-match-sonames libtidy5
E: tidy: unstripped-binary-or-object usr/bin/tidy
E: tidy: unstripped-binary-or-object usr/lib/libtidy.so.5.1.47
E: tidy: missing-dependency-on-libc needed by usr/bin/tidy and 1 others
E: tidy: changelog-file-missing-in-native-package
E: tidy: no-copyright-file
W: tidy: unknown-architecture armv7l
W: tidy: unknown-section base
E: tidy: manpage-not-compressed usr/share/man/man1/tidy.1
W: tidy: non-dev-pkg-with-shlib-symlink usr/lib/libtidy.so.5.1.47 usr/lib/libtidy.so
E: tidy: no-shlibs-control-file usr/lib/libtidy.so.5.1.47
E: tidy: postinst-must-call-ldconfig usr/lib/libtidy.so.5.1.47
=========================
```

I really seek some **HELP** for people who understand unix/linux a lot more than me... I would really like to be able to generate a **clean** DEB file for distribution...

**Comment by sataris** [comment]
@geoffmcl  

I'm far from being an expert on this, but I believe the error. 

```
W: tidy: package-name-doesnt-match-sonames libtidy5
```

Is caused by 

```
build/cmake/libtidy.so.5.1.47
```

This is where libtidy5 is coming from. If I change the line

```
Package: tidy
```

to  

```
Package: libtidy5
```

Then lintian no longer complains.

**Comment by geoffmcl** [comment]
@sataris thank you for the `Package: libtidy5` addition... This does indeed remove that first `lintian` warning...

On reading around, I also tried changing the the section to `Section: Libraries`, but `lintian` still thinks this is a problem?

That reading also lead me to trying `$ dpkg-architecture -L`, which lists a long list of, I supposed, acceptable architectures, but how to resolve this in the script? Then `$ dpkg-architecture -qDEB_HOST_MULTIARCH` yields `x86_64-linux-gnu`, which does not seem to be in the above list!

And that last command in RPI Raspbian yields `arm-linux-gnueabihf`?

Come on unix/linux packaging people! **Help us out here**!

Yes, I know it is Easter, and maybe you have other things to do, and I will be patient...

There **must** be a way to address each of these `lintain` issues...

Like running the CMake/CPack `make package` I can see it generates an `md5sums` file, with each of the files included are listed with an md5sum... Will this solve one of the problems?

All I want is a `simple` script to generate a fully acceptable DEB package... thanks...

**Comment by geoffmcl** [comment]
I have continued to experiment with this and removed some of the `lintian` warnings and errors - mainly -
- Added a `strip -s ...` to the script for two files
- Scripted gzip of tidy.1 man file
- Scripted adding an md5sums file, using `mkmd5sum.sh`

The latest script effort is here [mkdeb.sh](https://github.com/geoffmcl/cpack-test/blob/master/make-deb/mkdeb.sh), and [mkmd5sum.sh](https://github.com/geoffmcl/cpack-test/blob/master/make-deb/mkmd5sum.sh), and running the `mkdeb.sh` as root have reduced the list somewhat, but now get a `lintian` warning about this, but it seems to have removed all the `permission` and `owner` items -

```
mkdeb.sh: Appears a successful DEB build... tidy-5.1.47-armv7l.deb
mkdeb.sh: Doing: 'lintian tidy-5.1.47-armv7l.deb'
=========================
warning: the authors of lintian do not recommend running it with root privileges!
E: libtidy5: missing-dependency-on-libc needed by usr/bin/tidy and 1 others
E: libtidy5: changelog-file-missing-in-native-package
E: libtidy5: no-copyright-file
W: libtidy5: unknown-architecture armv7l
W: libtidy5: non-dev-pkg-with-shlib-symlink usr/lib/libtidy.so.5.1.47 usr/lib/libtidy.so
E: libtidy5: no-shlibs-control-file usr/lib/libtidy.so.5.1.47
E: libtidy5: postinst-must-call-ldconfig usr/lib/libtidy.so.5.1.47
=========================
```

This is an extract of the log in RPI Raspbian, but the Ubunutu list is very similar...

But still **seek help** in reducing it further...

**Comment by danielhjames** [comment]
Hi @geoffmcl @sataris I took a different approach with https://github.com/danielhjames/tidy-packaging as my aim is to get the new package into official Debian/Ubuntu.

I started from the old Debian files and updated/simplified them for Tidy 5.2.0. I have some test packages available for Debian sid and jessie amd64 in the 'debs' directory, or you could rebuild the package for your own distro from the orig.tar.gz with dpkg-buildpackage -us -uc

**Comment by balthisar** [comment]
@geoffmcl, Given that we're in the Debian repo now, can this issue be closed?

**Comment by geoffmcl** [comment]
@balthisar well given that this was originally about the 5.1.25 DEB we posted, I guess it can...

But I have **not** checked the later packages we generate for unix passes the lintian tests... but we can let that come up as a **new** issue, if there is a problem... thanks...
